const SHOPPER_TRUST_INDEX = 'SHOPPER_TRUST_INDEX'
const CHECKOUT_AND_REFUND = 'CHECKOUT_AND_REFUND'
const RETURNS_ORCHESTRATOR = 'RETURNS_ORCHESTRATOR'
const IDENTITY_AND_AUTHENTICATION = 'IDENTITY_AND_AUTHENTICATION'
const PAYMENT_PERSONALIZATION = 'PAYMENT_PERSONALIZATION'

export type config_type = 'LOW_RISK' | 'MEDIUM_RISK' | 'HIGH_RISK';

export { SHOPPER_TRUST_INDEX, PAYMENT_PERSONALIZATION, CHECKOUT_AND_REFUND, RETURNS_ORCHESTRATOR, IDENTITY_AND_AUTHENTICATION }